# Use this in your UnturnedImages/config.yaml file
- Id: "6000060000;6000560005;60010-60014;60017-60020;60022-60025" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2961182278/vehicles/{ItemId}.png" # The repository of the override.